//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNetworkAdministrator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Warning> Warning { get; set; }
        public virtual DbSet<WarningType> WarningType { get; set; }
        public virtual DbSet<DaysToCheck> DaysToCheck { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
