//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNetworkAdministrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring
    {
        public int Id { get; set; }
        public int CheckStatus { get; set; }
        public int LostingPackage { get; set; }
        public int NetworkUsingExtreme { get; set; }
        public int ProcessUsingExtreme { get; set; }
    }
}
