//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNetworkAdministrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status()
        {
            this.Good = 1;
            this.Slow = 2;
            this.Unreacheable = 3;
            this.NotTested = 4;
        }
    
        public int Id { get; set; }
        public int Good { get; set; }
        public int Slow { get; set; }
        public int Unreacheable { get; set; }
        public int NotTested { get; set; }
    }
}
