//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNetworkAdministrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int Id { get; set; }
        public string Computer { get; set; }
        public string Printer { get; set; }
        public string Switch { get; set; }
        public string Camera { get; set; }
        public string Unknown { get; set; }
    }
}
