//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNetworkAdministrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarningType()
        {
            this.Offline = "1";
            this.LostingPackage = "2";
            this.NetworkUsingExtreme = "3";
            this.ProcessUsingExtreme = "4";
            this.DiskUtilization = "5";
            this.Unknown = 6;
        }
    
        public int Id { get; set; }
        public string Offline { get; set; }
        public string LostingPackage { get; set; }
        public string NetworkUsingExtreme { get; set; }
        public string ProcessUsingExtreme { get; set; }
        public string DiskUtilization { get; set; }
        public int Unknown { get; set; }
    }
}
